
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.12.9
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
